version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/practice-app/backend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels: ["dependencies", "python"]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels: ["dependencies", "ci"]

  - package-ecosystem: "docker"
    directory: "/practice-app/backend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels: ["dependencies", "docker"]

  - package-ecosystem: "terraform"
    directory: "/practice-app/infra"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels: ["dependencies", "infra"]
